/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_OTA_OTA_Flash_Service_PROXY_HPP_
#define V1_COM_OTA_OTA_Flash_Service_PROXY_HPP_

#include <v1/com/ota/OTAFlashServiceProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace ota {

template <typename ... _AttributeExtensions>
class OTAFlashServiceProxy
    : virtual public OTAFlashService,
      virtual public OTAFlashServiceProxyBase,
      virtual public _AttributeExtensions... {
public:
    OTAFlashServiceProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~OTAFlashServiceProxy();

    typedef ::v1::com::ota::OTAFlashService InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute currentState.
     */
    virtual CurrentStateAttribute& getCurrentStateAttribute() {
        return delegate_->getCurrentStateAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute flashProgressPercent.
     */
    virtual FlashProgressPercentAttribute& getFlashProgressPercentAttribute() {
        return delegate_->getFlashProgressPercentAttribute();
    }
    /**
     * Calls startTransfer with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void startTransfer(uint64_t _imageSize, uint32_t _totalChunks, std::string _expectedChecksum, CommonAPI::CallStatus &_internalCallStatus, std::string &_transferId, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls startTransfer with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> startTransferAsync(const uint64_t &_imageSize, const uint32_t &_totalChunks, const std::string &_expectedChecksum, StartTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls sendChunk with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void sendChunk(std::string _transferId, uint32_t _chunkIndex, CommonAPI::ByteBuffer _chunkData, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls sendChunk with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> sendChunkAsync(const std::string &_transferId, const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_chunkData, SendChunkAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls finalizeTransfer with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void finalizeTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls finalizeTransfer with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> finalizeTransferAsync(const std::string &_transferId, FinalizeTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls cancelTransfer with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void cancelTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls cancelTransfer with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> cancelTransferAsync(const std::string &_transferId, CancelTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast FlashProgress.
     */
    virtual FlashProgressEvent& getFlashProgressEvent() {
        return delegate_->getFlashProgressEvent();
    }



 private:
    std::shared_ptr< OTAFlashServiceProxyBase> delegate_;
};

typedef OTAFlashServiceProxy<> OTAFlashServiceProxyDefault;

namespace OTAFlashServiceExtensions {
    template <template <typename > class _ExtensionType>
    class CurrentStateAttributeExtension {
     public:
        typedef _ExtensionType< OTAFlashServiceProxyBase::CurrentStateAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< OTAFlashServiceProxyBase::CurrentStateAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        CurrentStateAttributeExtension(OTAFlashServiceProxyBase& proxy): attributeExtension_(proxy.getCurrentStateAttribute()) {
        }
    
        inline extension_type& getCurrentStateAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class FlashProgressPercentAttributeExtension {
     public:
        typedef _ExtensionType< OTAFlashServiceProxyBase::FlashProgressPercentAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< OTAFlashServiceProxyBase::FlashProgressPercentAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        FlashProgressPercentAttributeExtension(OTAFlashServiceProxyBase& proxy): attributeExtension_(proxy.getFlashProgressPercentAttribute()) {
        }
    
        inline extension_type& getFlashProgressPercentAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace OTAFlashServiceExtensions

//
// OTAFlashServiceProxy Implementation
//
template <typename ... _AttributeExtensions>
OTAFlashServiceProxy<_AttributeExtensions...>::OTAFlashServiceProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< OTAFlashServiceProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< OTAFlashServiceProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
OTAFlashServiceProxy<_AttributeExtensions...>::~OTAFlashServiceProxy() {
}

template <typename ... _AttributeExtensions>
void OTAFlashServiceProxy<_AttributeExtensions...>::startTransfer(uint64_t _imageSize, uint32_t _totalChunks, std::string _expectedChecksum, CommonAPI::CallStatus &_internalCallStatus, std::string &_transferId, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    delegate_->startTransfer(_imageSize, _totalChunks, _expectedChecksum, _internalCallStatus, _transferId, _errorCode, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OTAFlashServiceProxy<_AttributeExtensions...>::startTransferAsync(const uint64_t &_imageSize, const uint32_t &_totalChunks, const std::string &_expectedChecksum, StartTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->startTransferAsync(_imageSize, _totalChunks, _expectedChecksum, _callback, _info);
}
template <typename ... _AttributeExtensions>
void OTAFlashServiceProxy<_AttributeExtensions...>::sendChunk(std::string _transferId, uint32_t _chunkIndex, CommonAPI::ByteBuffer _chunkData, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    delegate_->sendChunk(_transferId, _chunkIndex, _chunkData, _internalCallStatus, _errorCode, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OTAFlashServiceProxy<_AttributeExtensions...>::sendChunkAsync(const std::string &_transferId, const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_chunkData, SendChunkAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->sendChunkAsync(_transferId, _chunkIndex, _chunkData, _callback, _info);
}
template <typename ... _AttributeExtensions>
void OTAFlashServiceProxy<_AttributeExtensions...>::finalizeTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    delegate_->finalizeTransfer(_transferId, _internalCallStatus, _errorCode, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OTAFlashServiceProxy<_AttributeExtensions...>::finalizeTransferAsync(const std::string &_transferId, FinalizeTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->finalizeTransferAsync(_transferId, _callback, _info);
}
template <typename ... _AttributeExtensions>
void OTAFlashServiceProxy<_AttributeExtensions...>::cancelTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    delegate_->cancelTransfer(_transferId, _internalCallStatus, _errorCode, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OTAFlashServiceProxy<_AttributeExtensions...>::cancelTransferAsync(const std::string &_transferId, CancelTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->cancelTransferAsync(_transferId, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &OTAFlashServiceProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool OTAFlashServiceProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool OTAFlashServiceProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& OTAFlashServiceProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& OTAFlashServiceProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> OTAFlashServiceProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace ota
} // namespace com
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::com::ota::OTAFlashServiceProxy,
    _AttributeExtension> {
    typedef typename ::v1::com::ota::OTAFlashServiceProxy<
            ::v1::com::ota::OTAFlashServiceExtensions::CurrentStateAttributeExtension<_AttributeExtension>, 
            ::v1::com::ota::OTAFlashServiceExtensions::FlashProgressPercentAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_OTA_OTA_Flash_Service_PROXY_HPP_
