/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_OTA_OTA_Flash_Service_STUB_DEFAULT_HPP_
#define V1_COM_OTA_OTA_Flash_Service_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/ota/OTAFlashServiceStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace ota {

/**
 * Provides a default implementation for OTAFlashServiceStubRemoteEvent and
 * OTAFlashServiceStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT OTAFlashServiceStubDefault
    : public virtual OTAFlashServiceStub {
public:
    COMMONAPI_EXPORT OTAFlashServiceStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(OTAFlashService::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT OTAFlashServiceStubRemoteEvent* initStubAdapter(const std::shared_ptr< OTAFlashServiceStubAdapter> &_adapter) {
        CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const ::v1::com::ota::OTAFlashService::FlashState &getCurrentStateAttribute() {
        return currentStateAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const ::v1::com::ota::OTAFlashService::FlashState &getCurrentStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getCurrentStateAttribute();
    }
    COMMONAPI_EXPORT virtual void setCurrentStateAttribute(::v1::com::ota::OTAFlashService::FlashState _value) {
        (void)trySetCurrentStateAttribute(_value);
    }
    COMMONAPI_EXPORT virtual const uint8_t &getFlashProgressPercentAttribute() {
        return flashProgressPercentAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint8_t &getFlashProgressPercentAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFlashProgressPercentAttribute();
    }
    COMMONAPI_EXPORT virtual void setFlashProgressPercentAttribute(uint8_t _value) {
        (void)trySetFlashProgressPercentAttribute(_value);
    }
    COMMONAPI_EXPORT virtual void startTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, uint64_t _imageSize, uint32_t _totalChunks, std::string _expectedChecksum, startTransferReply_t _reply) {
        (void)_client;
        (void)_imageSize;
        (void)_totalChunks;
        (void)_expectedChecksum;
        std::string transferId = "";
        OTAFlashService::OTAErrorCode errorCode = OTAFlashService::OTAErrorCode::SUCCESS;
        if (!errorCode.validate()) {
            return;
        }
        _reply(transferId, errorCode);
    }
    COMMONAPI_EXPORT virtual void sendChunk(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _transferId, uint32_t _chunkIndex, CommonAPI::ByteBuffer _chunkData, sendChunkReply_t _reply) {
        (void)_client;
        (void)_transferId;
        (void)_chunkIndex;
        (void)_chunkData;
        OTAFlashService::OTAErrorCode errorCode = OTAFlashService::OTAErrorCode::SUCCESS;
        if (!errorCode.validate()) {
            return;
        }
        _reply(errorCode);
    }
    COMMONAPI_EXPORT virtual void finalizeTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _transferId, finalizeTransferReply_t _reply) {
        (void)_client;
        (void)_transferId;
        OTAFlashService::OTAErrorCode errorCode = OTAFlashService::OTAErrorCode::SUCCESS;
        if (!errorCode.validate()) {
            return;
        }
        _reply(errorCode);
    }
    COMMONAPI_EXPORT virtual void cancelTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _transferId, cancelTransferReply_t _reply) {
        (void)_client;
        (void)_transferId;
        OTAFlashService::OTAErrorCode errorCode = OTAFlashService::OTAErrorCode::SUCCESS;
        if (!errorCode.validate()) {
            return;
        }
        _reply(errorCode);
    }
    COMMONAPI_EXPORT virtual void fireFlashProgressEvent(const std::string &_transferId, const ::v1::com::ota::OTAFlashService::FlashState &_flashState, const uint8_t &_progressPercent, const ::v1::com::ota::OTAFlashService::OTAErrorCode &_errorCode) {
        if (!_flashState.validate()) {
            return;
        }
        if (!_errorCode.validate()) {
            return;
        }
        OTAFlashServiceStub::fireFlashProgressEvent(_transferId, _flashState, _progressPercent, _errorCode);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetCurrentStateAttribute(::v1::com::ota::OTAFlashService::FlashState _value) {
        if (!validateCurrentStateAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<OTAFlashServiceStubAdapter> stubAdapter = CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockCurrentStateAttribute(true);
            valueChanged = (currentStateAttributeValue_ != _value);
            currentStateAttributeValue_ = std::move(_value);
            stubAdapter->lockCurrentStateAttribute(false);
        } else {
            valueChanged = (currentStateAttributeValue_ != _value);
            currentStateAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateCurrentStateAttributeRequestedValue(const ::v1::com::ota::OTAFlashService::FlashState &_value) {
        (void)_value;
        return _value.validate();
    }
    COMMONAPI_EXPORT virtual bool trySetFlashProgressPercentAttribute(uint8_t _value) {
        if (!validateFlashProgressPercentAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<OTAFlashServiceStubAdapter> stubAdapter = CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFlashProgressPercentAttribute(true);
            valueChanged = (flashProgressPercentAttributeValue_ != _value);
            flashProgressPercentAttributeValue_ = std::move(_value);
            stubAdapter->lockFlashProgressPercentAttribute(false);
        } else {
            valueChanged = (flashProgressPercentAttributeValue_ != _value);
            flashProgressPercentAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFlashProgressPercentAttributeRequestedValue(const uint8_t &_value) {
        (void)_value;
        return true;
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual OTAFlashServiceStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(OTAFlashServiceStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        OTAFlashServiceStubDefault *defaultStub_;
    };
protected:
    OTAFlashServiceStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    ::v1::com::ota::OTAFlashService::FlashState currentStateAttributeValue_ {};
    uint8_t flashProgressPercentAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace ota
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_OTA_OTA_Flash_Service_STUB_DEFAULT
