/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/ota/OTAFlashServiceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace ota {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createOTAFlashServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< OTAFlashServiceSomeIPProxy>(_address, _connection);
}

void initializeOTAFlashServiceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:com.ota.OTAFlashService:v1_0:com.ota.OTAFlashService",
        0x100, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "com.ota.OTAFlashService:v1_0",
        &createOTAFlashServiceSomeIPProxy);
}

INITIALIZER(registerOTAFlashServiceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeOTAFlashServiceSomeIPProxy);
}

OTAFlashServiceSomeIPProxy::OTAFlashServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          currentState_(*this, CommonAPI::SomeIP::method_id_t(0x0), false, false, &::v1::com::ota::OTAFlashService_::FlashStateDeployment),
          flashProgressPercent_(*this, CommonAPI::SomeIP::method_id_t(0x0), false, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
          flashProgress_(*this, 0x1, CommonAPI::SomeIP::event_id_t(0x8001), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), &::v1::com::ota::OTAFlashService_::FlashStateDeployment, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), &::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment))
{
}

OTAFlashServiceSomeIPProxy::~OTAFlashServiceSomeIPProxy() {
}

OTAFlashServiceSomeIPProxy::CurrentStateAttribute& OTAFlashServiceSomeIPProxy::getCurrentStateAttribute() {
    return currentState_;
}
OTAFlashServiceSomeIPProxy::FlashProgressPercentAttribute& OTAFlashServiceSomeIPProxy::getFlashProgressPercentAttribute() {
    return flashProgressPercent_;
}

OTAFlashServiceSomeIPProxy::FlashProgressEvent& OTAFlashServiceSomeIPProxy::getFlashProgressEvent() {
    return flashProgress_;
}

void OTAFlashServiceSomeIPProxy::startTransfer(uint64_t _imageSize, uint32_t _totalChunks, std::string _expectedChecksum, CommonAPI::CallStatus &_internalCallStatus, std::string &_transferId, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint64_t, CommonAPI::SomeIP::IntegerDeployment<uint64_t>> deploy_imageSize(_imageSize, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint64_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_totalChunks(_totalChunks, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_expectedChecksum(_expectedChecksum, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint64_t,
                CommonAPI::SomeIP::IntegerDeployment<uint64_t>
            >,
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_imageSize, deploy_totalChunks, deploy_expectedChecksum,
        _internalCallStatus,
        deploy_transferId, deploy_errorCode);
    _transferId = deploy_transferId.getValue();
    _errorCode = deploy_errorCode.getValue();
}

std::future<CommonAPI::CallStatus> OTAFlashServiceSomeIPProxy::startTransferAsync(const uint64_t &_imageSize, const uint32_t &_totalChunks, const std::string &_expectedChecksum, StartTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint64_t, CommonAPI::SomeIP::IntegerDeployment<uint64_t>> deploy_imageSize(_imageSize, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint64_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_totalChunks(_totalChunks, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_expectedChecksum(_expectedChecksum, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint64_t,
                CommonAPI::SomeIP::IntegerDeployment<uint64_t>
            >,
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >,
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_imageSize, deploy_totalChunks, deploy_expectedChecksum,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _transferId, CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t > _errorCode) {
            if (_callback)
                _callback(_internalCallStatus, _transferId.getValue(), _errorCode.getValue());
        },
        std::make_tuple(deploy_transferId, deploy_errorCode));
}

void OTAFlashServiceSomeIPProxy::sendChunk(std::string _transferId, uint32_t _chunkIndex, CommonAPI::ByteBuffer _chunkData, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_chunkIndex(_chunkIndex, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment> deploy_chunkData(_chunkData, &::v1::com::ota::OTAFlashService_::sendChunk_chunkDataDeployment);
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >,
            CommonAPI::Deployable<
                CommonAPI::ByteBuffer,
                CommonAPI::SomeIP::ByteBufferDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_transferId, deploy_chunkIndex, deploy_chunkData,
        _internalCallStatus,
        deploy_errorCode);
    _errorCode = deploy_errorCode.getValue();
}

std::future<CommonAPI::CallStatus> OTAFlashServiceSomeIPProxy::sendChunkAsync(const std::string &_transferId, const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_chunkData, SendChunkAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_chunkIndex(_chunkIndex, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment> deploy_chunkData(_chunkData, &::v1::com::ota::OTAFlashService_::sendChunk_chunkDataDeployment);
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >,
            CommonAPI::Deployable<
                CommonAPI::ByteBuffer,
                CommonAPI::SomeIP::ByteBufferDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_transferId, deploy_chunkIndex, deploy_chunkData,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t > _errorCode) {
            if (_callback)
                _callback(_internalCallStatus, _errorCode.getValue());
        },
        std::make_tuple(deploy_errorCode));
}

void OTAFlashServiceSomeIPProxy::finalizeTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_transferId,
        _internalCallStatus,
        deploy_errorCode);
    _errorCode = deploy_errorCode.getValue();
}

std::future<CommonAPI::CallStatus> OTAFlashServiceSomeIPProxy::finalizeTransferAsync(const std::string &_transferId, FinalizeTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_transferId,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t > _errorCode) {
            if (_callback)
                _callback(_internalCallStatus, _errorCode.getValue());
        },
        std::make_tuple(deploy_errorCode));
}

void OTAFlashServiceSomeIPProxy::cancelTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x5),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_transferId,
        _internalCallStatus,
        deploy_errorCode);
    _errorCode = deploy_errorCode.getValue();
}

std::future<CommonAPI::CallStatus> OTAFlashServiceSomeIPProxy::cancelTransferAsync(const std::string &_transferId, CancelTransferAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deploy_errorCode(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                OTAFlashService::OTAErrorCode,
                ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x5),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_transferId,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t > _errorCode) {
            if (_callback)
                _callback(_internalCallStatus, _errorCode.getValue());
        },
        std::make_tuple(deploy_errorCode));
}

void OTAFlashServiceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> OTAFlashServiceSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace ota
} // namespace com
} // namespace v1
