/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_OTA_OTA_FLASH_SERVICE_HPP_
#define V1_COM_OTA_OTA_FLASH_SERVICE_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace ota {

class OTAFlashService {
public:
    virtual ~OTAFlashService() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct OTAErrorCode : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SUCCESS = 0,
            INVALID_TRANSFER_ID = 1,
            CHUNK_OUT_OF_ORDER = 2,
            CHECKSUM_MISMATCH = 3,
            FLASH_WRITE_ERROR = 4,
            PARTITION_BUSY = 5,
            STORAGE_FULL = 6,
            TRANSFER_TIMEOUT = 7,
            TRANSFER_IN_PROGRESS = 8,
            INVALID_PARAMETER = 9,
            INCOMPLETE_TRANSFER = 10
        };
    
        OTAErrorCode()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SUCCESS)) {}
        OTAErrorCode(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SUCCESS):
                case static_cast< uint8_t>(Literal::INVALID_TRANSFER_ID):
                case static_cast< uint8_t>(Literal::CHUNK_OUT_OF_ORDER):
                case static_cast< uint8_t>(Literal::CHECKSUM_MISMATCH):
                case static_cast< uint8_t>(Literal::FLASH_WRITE_ERROR):
                case static_cast< uint8_t>(Literal::PARTITION_BUSY):
                case static_cast< uint8_t>(Literal::STORAGE_FULL):
                case static_cast< uint8_t>(Literal::TRANSFER_TIMEOUT):
                case static_cast< uint8_t>(Literal::TRANSFER_IN_PROGRESS):
                case static_cast< uint8_t>(Literal::INVALID_PARAMETER):
                case static_cast< uint8_t>(Literal::INCOMPLETE_TRANSFER):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const OTAErrorCode &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const OTAErrorCode &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const OTAErrorCode &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const OTAErrorCode &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const OTAErrorCode &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const OTAErrorCode &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SUCCESS): return "SUCCESS";
            case static_cast< uint8_t>(Literal::INVALID_TRANSFER_ID): return "INVALID_TRANSFER_ID";
            case static_cast< uint8_t>(Literal::CHUNK_OUT_OF_ORDER): return "CHUNK_OUT_OF_ORDER";
            case static_cast< uint8_t>(Literal::CHECKSUM_MISMATCH): return "CHECKSUM_MISMATCH";
            case static_cast< uint8_t>(Literal::FLASH_WRITE_ERROR): return "FLASH_WRITE_ERROR";
            case static_cast< uint8_t>(Literal::PARTITION_BUSY): return "PARTITION_BUSY";
            case static_cast< uint8_t>(Literal::STORAGE_FULL): return "STORAGE_FULL";
            case static_cast< uint8_t>(Literal::TRANSFER_TIMEOUT): return "TRANSFER_TIMEOUT";
            case static_cast< uint8_t>(Literal::TRANSFER_IN_PROGRESS): return "TRANSFER_IN_PROGRESS";
            case static_cast< uint8_t>(Literal::INVALID_PARAMETER): return "INVALID_PARAMETER";
            case static_cast< uint8_t>(Literal::INCOMPLETE_TRANSFER): return "INCOMPLETE_TRANSFER";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct FlashState : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            IDLE = 0,
            RECEIVING = 1,
            VERIFYING = 2,
            FLASHING = 3,
            REBOOTING = 4,
            COMPLETE = 5,
            FAILED = 6
        };
    
        FlashState()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::IDLE)) {}
        FlashState(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::IDLE):
                case static_cast< uint8_t>(Literal::RECEIVING):
                case static_cast< uint8_t>(Literal::VERIFYING):
                case static_cast< uint8_t>(Literal::FLASHING):
                case static_cast< uint8_t>(Literal::REBOOTING):
                case static_cast< uint8_t>(Literal::COMPLETE):
                case static_cast< uint8_t>(Literal::FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const FlashState &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const FlashState &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const FlashState &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const FlashState &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const FlashState &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const FlashState &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::IDLE): return "IDLE";
            case static_cast< uint8_t>(Literal::RECEIVING): return "RECEIVING";
            case static_cast< uint8_t>(Literal::VERIFYING): return "VERIFYING";
            case static_cast< uint8_t>(Literal::FLASHING): return "FLASHING";
            case static_cast< uint8_t>(Literal::REBOOTING): return "REBOOTING";
            case static_cast< uint8_t>(Literal::COMPLETE): return "COMPLETE";
            case static_cast< uint8_t>(Literal::FAILED): return "FAILED";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* OTAFlashService::getInterface() {
    return ("com.ota.OTAFlashService:v1_0");
}

CommonAPI::Version OTAFlashService::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace ota
} // namespace com
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_OTA_OTA_FLASH_SERVICE_HPP_
