/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_OTA_OTA_FLASH_SERVICE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COM_OTA_OTA_FLASH_SERVICE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/com/ota/OTAFlashServiceStub.hpp>
#include <v1/com/ota/OTAFlashServiceSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace ota {

template <typename _Stub = ::v1::com::ota::OTAFlashServiceStub, typename... _Stubs>
class OTAFlashServiceSomeIPStubAdapterInternal
    : public virtual OTAFlashServiceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< OTAFlashServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> OTAFlashServiceSomeIPStubAdapterHelper;

    ~OTAFlashServiceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        OTAFlashServiceSomeIPStubAdapterHelper::deinit();
    }

    void fireFlashProgressEvent(const std::string &_transferId, const ::v1::com::ota::OTAFlashService::FlashState &_flashState, const uint8_t &_progressPercent, const ::v1::com::ota::OTAFlashService::OTAErrorCode &_errorCode);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        CommonAPI::Version
    > getOTAFlashServiceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        ::v1::com::ota::OTAFlashService::FlashState,
        ::v1::com::ota::OTAFlashService_::FlashStateDeployment_t
    > getCurrentStateAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > getFlashProgressPercentAttributeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        std::tuple< uint64_t, uint32_t, std::string>,
        std::tuple< std::string, OTAFlashService::OTAErrorCode>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint64_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t>
    > startTransferStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        std::tuple< std::string, uint32_t, CommonAPI::ByteBuffer>,
        std::tuple< OTAFlashService::OTAErrorCode>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ByteBufferDeployment>,
        std::tuple< ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t>
    > sendChunkStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        std::tuple< std::string>,
        std::tuple< OTAFlashService::OTAErrorCode>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t>
    > finalizeTransferStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::ota::OTAFlashServiceStub,
        std::tuple< std::string>,
        std::tuple< OTAFlashService::OTAErrorCode>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t>
    > cancelTransferStubDispatcher;
    
    OTAFlashServiceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        OTAFlashServiceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< OTAFlashServiceStub>(_stub)),
        getOTAFlashServiceInterfaceVersionStubDispatcher(&OTAFlashServiceStub::lockInterfaceVersionAttribute, &OTAFlashServiceStub::getInterfaceVersion, false, true),
        getCurrentStateAttributeStubDispatcher(
            &::v1::com::ota::OTAFlashServiceStub::lockCurrentStateAttribute,
            &::v1::com::ota::OTAFlashServiceStub::getCurrentStateAttribute,
            false,
            _stub->hasElement(0), &::v1::com::ota::OTAFlashService_::FlashStateDeployment)
        ,
        getFlashProgressPercentAttributeStubDispatcher(
            &::v1::com::ota::OTAFlashServiceStub::lockFlashProgressPercentAttribute,
            &::v1::com::ota::OTAFlashServiceStub::getFlashProgressPercentAttribute,
            false,
            _stub->hasElement(1))
        ,
        startTransferStubDispatcher(
            &OTAFlashServiceStub::startTransfer,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint64_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), &::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment))
        
        ,
        sendChunkStubDispatcher(
            &OTAFlashServiceStub::sendChunk,
            false,
            _stub->hasElement(3),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::com::ota::OTAFlashService_::sendChunk_chunkDataDeployment),
            std::make_tuple(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment))
        
        ,
        finalizeTransferStubDispatcher(
            &OTAFlashServiceStub::finalizeTransfer,
            false,
            _stub->hasElement(4),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment))
        
        ,
        cancelTransferStubDispatcher(
            &OTAFlashServiceStub::cancelTransfer,
            false,
            _stub->hasElement(5),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(&::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment))
        
    {
        OTAFlashServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x0) }, &getCurrentStateAttributeStubDispatcher );
        OTAFlashServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x0) }, &getFlashProgressPercentAttributeStubDispatcher );
        OTAFlashServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &startTransferStubDispatcher );
        OTAFlashServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2) }, &sendChunkStubDispatcher );
        OTAFlashServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3) }, &finalizeTransferStubDispatcher );
        OTAFlashServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5) }, &cancelTransferStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x1));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8001), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void OTAFlashServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFlashProgressEvent(const std::string &_transferId, const ::v1::com::ota::OTAFlashService::FlashState &_flashState, const uint8_t &_progressPercent, const ::v1::com::ota::OTAFlashService::OTAErrorCode &_errorCode) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_transferId(_transferId, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::FlashState, ::v1::com::ota::OTAFlashService_::FlashStateDeployment_t> deployed_flashState(_flashState, &::v1::com::ota::OTAFlashService_::FlashStateDeployment);
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_progressPercent(_progressPercent, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::Deployable< OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t> deployed_errorCode(_errorCode, &::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment);
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    ,  CommonAPI::Deployable< ::v1::com::ota::OTAFlashService::FlashState, ::v1::com::ota::OTAFlashService_::FlashStateDeployment_t > 
    ,  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    ,  CommonAPI::Deployable< ::v1::com::ota::OTAFlashService::OTAErrorCode, ::v1::com::ota::OTAFlashService_::OTAErrorCodeDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8001),
            false,
             deployed_transferId 
            ,  deployed_flashState 
            ,  deployed_progressPercent 
            ,  deployed_errorCode 
    );
}


template <typename _Stub, typename... _Stubs>
void OTAFlashServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void OTAFlashServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::com::ota::OTAFlashServiceStub, typename... _Stubs>
class OTAFlashServiceSomeIPStubAdapter
    : public OTAFlashServiceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    OTAFlashServiceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          OTAFlashServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace ota
} // namespace com
} // namespace v1

#endif // V1_COM_OTA_OTA_Flash_Service_SOMEIP_STUB_ADAPTER_HPP_
