/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_OTA_OTA_Flash_Service_STUB_HPP_
#define V1_COM_OTA_OTA_Flash_Service_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/com/ota/OTAFlashService.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace ota {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service OTAFlashService. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class OTAFlashServiceStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual OTAFlashService {
 public:
    /**
    * Sends a broadcast event for FlashProgress. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireFlashProgressEvent(const std::string &_transferId, const ::v1::com::ota::OTAFlashService::FlashState &_flashState, const uint8_t &_progressPercent, const ::v1::com::ota::OTAFlashService::OTAErrorCode &_errorCode) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockCurrentStateAttribute(bool _lockAccess) {
        if (_lockAccess) {
            currentStateMutex_.lock();
        } else {
            currentStateMutex_.unlock();
        }
    }
    void lockFlashProgressPercentAttribute(bool _lockAccess) {
        if (_lockAccess) {
            flashProgressPercentMutex_.lock();
        } else {
            flashProgressPercentMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex currentStateMutex_;
    std::recursive_mutex flashProgressPercentMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for OTAFlashService.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class OTAFlashServiceStubRemoteEvent
{
public:
    virtual ~OTAFlashServiceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service OTAFlashService to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class OTAFlashServiceStub
    : public virtual CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>
{
public:
    typedef std::function<void (std::string _transferId, OTAFlashService::OTAErrorCode _errorCode)> startTransferReply_t;
    typedef std::function<void (OTAFlashService::OTAErrorCode _errorCode)> sendChunkReply_t;
    typedef std::function<void (OTAFlashService::OTAErrorCode _errorCode)> finalizeTransferReply_t;
    typedef std::function<void (OTAFlashService::OTAErrorCode _errorCode)> cancelTransferReply_t;

    virtual ~OTAFlashServiceStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 7);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute currentState
    virtual const ::v1::com::ota::OTAFlashService::FlashState &getCurrentStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    void lockCurrentStateAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockCurrentStateAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute flashProgressPercent
    virtual const uint8_t &getFlashProgressPercentAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    void lockFlashProgressPercentAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockFlashProgressPercentAttribute(_lockAccess);
    }
    /// This is the method that will be called on remote calls on the method startTransfer.
    virtual void startTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, uint64_t _imageSize, uint32_t _totalChunks, std::string _expectedChecksum, startTransferReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method sendChunk.
    virtual void sendChunk(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _transferId, uint32_t _chunkIndex, CommonAPI::ByteBuffer _chunkData, sendChunkReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method finalizeTransfer.
    virtual void finalizeTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _transferId, finalizeTransferReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method cancelTransfer.
    virtual void cancelTransfer(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _transferId, cancelTransferReply_t _reply) = 0;
    /// Sends a broadcast event for FlashProgress.
    virtual void fireFlashProgressEvent(const std::string &_transferId, const ::v1::com::ota::OTAFlashService::FlashState &_flashState, const uint8_t &_progressPercent, const ::v1::com::ota::OTAFlashService::OTAErrorCode &_errorCode) {
        auto stubAdapter = CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireFlashProgressEvent(_transferId, _flashState, _progressPercent, _errorCode);
    }


    using CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<OTAFlashServiceStubAdapter, OTAFlashServiceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef OTAFlashServiceStubRemoteEvent RemoteEventType;
    typedef ::v1::com::ota::OTAFlashService StubInterface;
};

} // namespace ota
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_OTA_OTA_Flash_Service_STUB_HPP_
