/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_OTA_OTA_Flash_Service_PROXY_BASE_HPP_
#define V1_COM_OTA_OTA_Flash_Service_PROXY_BASE_HPP_

#include <v1/com/ota/OTAFlashService.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace ota {

class OTAFlashServiceProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ReadonlyAttribute<::v1::com::ota::OTAFlashService::FlashState> CurrentStateAttribute;
    typedef CommonAPI::ReadonlyAttribute<uint8_t> FlashProgressPercentAttribute;
    typedef CommonAPI::Event<
        std::string, ::v1::com::ota::OTAFlashService::FlashState, uint8_t, ::v1::com::ota::OTAFlashService::OTAErrorCode
    > FlashProgressEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&, const OTAFlashService::OTAErrorCode&)> StartTransferAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const OTAFlashService::OTAErrorCode&)> SendChunkAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const OTAFlashService::OTAErrorCode&)> FinalizeTransferAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const OTAFlashService::OTAErrorCode&)> CancelTransferAsyncCallback;

    virtual CurrentStateAttribute& getCurrentStateAttribute() = 0;
    virtual FlashProgressPercentAttribute& getFlashProgressPercentAttribute() = 0;
    virtual void startTransfer(uint64_t _imageSize, uint32_t _totalChunks, std::string _expectedChecksum, CommonAPI::CallStatus &_internalCallStatus, std::string &_transferId, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> startTransferAsync(const uint64_t &_imageSize, const uint32_t &_totalChunks, const std::string &_expectedChecksum, StartTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void sendChunk(std::string _transferId, uint32_t _chunkIndex, CommonAPI::ByteBuffer _chunkData, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> sendChunkAsync(const std::string &_transferId, const uint32_t &_chunkIndex, const CommonAPI::ByteBuffer &_chunkData, SendChunkAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void finalizeTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> finalizeTransferAsync(const std::string &_transferId, FinalizeTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void cancelTransfer(std::string _transferId, CommonAPI::CallStatus &_internalCallStatus, OTAFlashService::OTAErrorCode &_errorCode, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> cancelTransferAsync(const std::string &_transferId, CancelTransferAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual FlashProgressEvent& getFlashProgressEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace ota
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_OTA_OTA_Flash_Service_PROXY_BASE_HPP_
