/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/ota/OTAFlashServiceSomeIPDeployment.hpp>

namespace v1 {
namespace com {
namespace ota {
namespace OTAFlashService_ {

// Type-specific deployments
OTAErrorCodeDeployment_t OTAErrorCodeDeployment(32, false);
FlashStateDeployment_t FlashStateDeployment(32, false);

// Attribute-specific deployments

// Argument-specific deployment
CommonAPI::SomeIP::ByteBufferDeployment sendChunk_chunkDataDeployment(0, 65536, 4);

// Broadcast-specific deployments

} // namespace OTAFlashService_
} // namespace ota
} // namespace com
} // namespace v1
